version: '3'
services:
  devcontainer:
    image: ${CI_REGISTRY_IMAGE}/devcontainer:${DOCKER_TAG}
    #command: ["--init", "--env-file", ".devcontainer/devcontainer.env"]
    volumes:
      - ..:/workspaces/primary:delegated
      - ${HOME}/.ssh:/home/vscode/.ssh
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker-host.sock
      - ${HOME}/.github:/home/vscode/.github
    environment:
      - "LOCAL_WORKSPACE_FOLDER=/workspaces/primary"
      - "GITHUB_WORKFLOW_INSTANCE_URL=https://github.com"
    init: true
